apps/goods/urls.py
from django.urls import path
from . import views


app_name = 'goods'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),  # 首页
    path('goods/<str:spu_id>/<str:sku_id>', views.DetailView.as_view(), name='detail'),  # 详情页
    path('list/<str:type_id>/<int:page>', views.ListView.as_view(), name='list'),  # 列表页
    path('search', views.GoodsSearchView.as_view(), name='search'),  # 全文检索框架
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.urls import register_converter
# from utils.converters import UsernameConverter


# register_converter(UsernameConverter, 'username')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('apps.goods.urls'), name='goods'),  # 商品模块
    path('cart/', include('apps.cart.urls'), name='cart'),  # 购物车模块
    path('order/', include('apps.order.urls'), name='order'),  # 订单模块
    path('user/', include('apps.user.urls'), name='user'),  # 用户模块
    path('captcha/', include('apps.captcha.urls'), name='captcha'),
]

apps/goods/models.py
from django.db import models
from db.base_model import BaseModel
from tinymce.models import HTMLField


class GoodsType(BaseModel):
    """商品类型模型类"""
    goods_type = models.CharField(max_length=20, verbose_name='商品类型')
    logo = models.CharField(max_length=20, blank=True, verbose_name='logo标识')
    image = models.ImageField(upload_to='goods_type_images', blank=True, verbose_name='商品类型图片路径')

    class Meta:
        db_table = 'ec_goods_type'
        verbose_name = '商品类型'
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.goods_type)


class GoodsSPU(BaseModel):
    XIAJIA = 0
    SHANGJIA = 1

    """商品SPU模型类"""
    GOODS_STATUS_CHOICES = (
        (XIAJIA, '下架'),
        (SHANGJIA, '上架'),
    )

    type = models.ForeignKey('goods.GoodsType', verbose_name='商品种类', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name='商品SPU')
    desc = models.JSONField(blank=True, verbose_name='商品介绍')
    detail = HTMLField(blank=True, verbose_name='商品详情')
    status = models.SmallIntegerField(default=SHANGJIA, choices=GOODS_STATUS_CHOICES, verbose_name='商品状态')

    class Meta:
        db_table = 'ec_goods_spu'
        verbose_name = '商品SPU'
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.name)


class GoodsSKU(BaseModel):
    """商品SKU模型类"""
    spu = models.ForeignKey('goods.GoodsSPU', verbose_name='商品SPU', on_delete=models.CASCADE)
    # name = models.CharField(max_length=100, verbose_name='商品SKU')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品单价')
    stock = models.IntegerField(default=1, verbose_name='商品库存')
    sales = models.IntegerField(default=0, verbose_name='商品销量')
    unite = models.CharField(max_length=20, verbose_name='商品单位')
    category = models.CharField(max_length=50, verbose_name="商品系列规格型号")

    class Meta:
        db_table = 'ec_goods_sku'
        verbose_name = '商品SKU'
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.spu) + str(self.category)


class GoodsImage(BaseModel):
    """商品图片模型类"""
    sku = models.ForeignKey('goods.GoodsSKU', verbose_name='商品SKU', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='goods_images', verbose_name='商品图片路径')

    class Meta:
        db_table = 'ec_goods_image'
        verbose_name = '商品图片'
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.sku)


class IndexGoodsBanner(BaseModel):
    """首页轮播商品展示模型类"""
    sku = models.ForeignKey('goods.GoodsSKU', verbose_name='商品SKU', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='banner_images', verbose_name='首页焦点图图片')
    index = models.SmallIntegerField(default=0, verbose_name='展示顺序')

    class Meta:
        db_table = 'ec_index_banner'
        verbose_name = '首页焦点图轮播商品'
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.sku)


# class IndexTypeGoodsBanner(BaseModel):
#     """首页分类商品展示模型类"""
#     DISPLAY_TYPE_CHOICES = (
#         (0, '标题'),
#         (1, '图片'),
#     )

#     type = models.ForeignKey('goods.GoodsType', verbose_name='商品类型', on_delete=models.CASCADE)
#     sku = models.ForeignKey('goods.GoodsSKU', verbose_name='商品SKU', on_delete=models.CASCADE)
#     display_type = models.SmallIntegerField(default=1, choices=DISPLAY_TYPE_CHOICES, verbose_name='展示类型')
#     index = models.SmallIntegerField(default=0, verbose_name='展示顺序')

#     class Meta:
#         db_table = 'ec_index_goods_type_show'
#         verbose_name = '主页分类展示商品'
#         verbose_name_plural = verbose_name

#     def __str__(self):
#         return str(self.type) + '-' + str(self.sku)


class IndexPromotionBanner(BaseModel):
    """首页促销活动模型类"""
    name = models.CharField(max_length=100, verbose_name='活动名称')
    url = models.CharField(max_length=255, verbose_name='活动链接')
    image = models.ImageField(upload_to='banner_images', verbose_name='活动图片')
    index = models.SmallIntegerField(default=0, verbose_name='展示顺序')

    class Meta:
        db_table = 'ec_index_promotion'
        verbose_name = '主页促销活动'
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.name)

templates/search/search.html
{% extends 'base_detail_list.html' %}
{% block title %}天天图书-商品搜索结果列表{% endblock title %}
{% block main_content %}
	<div class="breadcrumb">
		<span>{{ query }}</span>
		<span>></span>
        <span>搜索结果如下</span>>
	</div>

	<div class="main_wrap clearfix">
        <ul class="goods_type_list clearfix">
            {% for item in page_obj %}
            <li>
                <a href="{% url 'goods:detail' item.object.spu.id item.object.id %}">
                    {% for image in item.object.goodsimage_set.all %}
                    {% if forloop.counter == 1%}
                    <img src="{{ image.image.url }}" alt="商品图片"></a>
                    {% endif %}
                    {% endfor %}
                <h4><a href="{% url 'goods:detail' item.object.spu.id item.object.id %}">{{ item.object.spu.name }}</a></h4>

                <div class="operate">
                    <span class="prize">￥{{ item.object.price }}</span>
                    <span class="unit">{{ item.object.unite }}</span>
                </div>
            </li>
            {% endfor %}
        </ul>

        <div class="pagenation">
            {% if page_obj.has_previous %}
            <a href="/search?q={{ query }}&page={{ page_obj.previous_page_number }}"><上一页</a>
            {% endif %}
            {% for pindex in paginator.page_range %}
                {% if pindex == page_obj.number %}
                    <a href="/search?q={{ query }}&page={{ pindex }}" class="active">{{ pindex }}</a>
                {% else %}
                    <a href="/search?q={{ query }}&page={{ pindex }}">{{ pindex }}</a>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <a href="/search?q={{ query }}&page={{ page_obj.next_page_number }}">下一页></a>
            {% endif %}
        </div>
	</div>

{% endblock main_content %}

templates/search/search_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
搜索的关键字：{{ query }}<br>
当前页的Page对象：{{ page }}<br>
<ul>
    {% for item in page %}
        <li>{{ item.object }}</li>
    {% endfor %}
</ul>
分页的paginator对象：{{ paginator }}<br>
</body>
</html>