apps/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'
urlpatterns = [
    path('add', views.CartAddView.as_view(), name='add'),  # 购物车记录添加
    path('', views.CartInfoView.as_view(), name='show'),  # 购物车页面显示
    path('update', views.CartUpdateView.as_view(), name='update'),  # 购物车记录更新
    path('delete', views.CartDeleteView.as_view(), name='delete'),  # 删除购物车记录
]

apps/chart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('bar/', views.ChartView.as_view(), name='demo'),
    path('pie/', views.PieChartView.as_view(), name='demo'),
    path('index/', views.IndexView.as_view(), name='demo'),
]

apps/goods/urls.py
from django.urls import path
from . import views


app_name = 'goods'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),  # 首页
    path('goods/<str:spu_id>/<str:sku_id>', views.DetailView.as_view(), name='detail'),  # 详情页
    path('list/<str:type_id>/<int:page>', views.ListView.as_view(), name='list'),  # 列表页
    path('search', views.GoodsSearchView.as_view(), name='search'),  # 全文检索框架
]

apps/order/urls.py
from django.urls import path
from . import views

app_name = 'order'
urlpatterns = [
    path('place', views.OrderPlaceView.as_view(), name='place'),  # 提交订单页面
    path('buy', views.BuyPlaceView.as_view(), name='buy'),  # 立即购买按钮
    path('commit', views.OrderCommitView.as_view(), name='commit'),  # 订单创建
    path('pay', views.OrderPayView.as_view(), name='pay'),  # 订单支付
    path('check', views.OrderCheckView.as_view(), name='check'),  # 查询交易结果
    path('comment/<str:order_id>', views.CommentView.as_view(), name='comment'),  # 订单评论
]

apps/user/urls.py
from django.urls import path
from . import views


app_name = 'user'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),  # 注册
    path('active/<str:token>', views.ActiveView.as_view(), name='active'),  # 用户激活
    path('login/', views.LoginView.as_view(), name='login'),  # 登录
    path('logout/', views.LogoutView.as_view(), name='logout'),  # 退出登录
    path('profile/', views.ProfileView.as_view(), name='profile'),  # 用户中心-信息页
    path('order/<int:page>', views.UserOrderView.as_view(), name='order'),  # 用户中心-订单页
    path('address/', views.AddressView.as_view(), name='address'),  # 用户中心-地址页
    path('favorite/', views.FavoriteView.as_view(), name='favorite'),  # 用户收藏
    path('favorite/<int:page>', views.FavoriteView.as_view(), name='favorite'),  # 用户收藏
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.urls import register_converter
# from utils.converters import UsernameConverter


# register_converter(UsernameConverter, 'username')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('apps.goods.urls'), name='goods'),  # 商品模块
    path('cart/', include('apps.cart.urls'), name='cart'),  # 购物车模块
    path('order/', include('apps.order.urls'), name='order'),  # 订单模块
    path('user/', include('apps.user.urls'), name='user'),  # 用户模块
    path('captcha/', include('apps.captcha.urls'), name='captcha'),
]

apps/chart/models.py
from django.db import models

# Create your models here.

apps/cart/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views.generic import View
from django_redis import get_redis_connection
from django.contrib.auth.mixins import LoginRequiredMixin

from apps.goods.models import GoodsSKU, GoodsImage


# 添加到购物车
# 1.请求方式，采用ajax,post
# 涉及数据的修改（增删改查），采用post
# 涉及数据的获取，采用get
# 2.传递参数：商品id（sku_id） 商品数量（count）

class CartInfoView(LoginRequiredMixin, View):
    """购物车页面显示"""

    def get(self, request):
        # 获取登录的用户
        user = request.user

        # 获取用户购物车中商品的信息
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # 返回字典{'商品id': 商品数量}
        cart_dict = conn.hgetall(cart_key)

        # 遍历获取商品的信息
        skus = list()
        # 保存用户购物车中商品的总数目和总价格
        total_count = 0
        total_price = 0
        for sku_id, count in cart_dict.items():
            # 根据商品的id获取商品的信息
            sku = GoodsSKU.objects.get(id=sku_id, is_delete=False)
            sku.images = GoodsImage.objects.filter(sku=sku, is_delete=False)
            # 计算商品的小计 动态给sku对象增加一个属性amount
            sku.amount = sku.price * int(count)
            # 动态给sku对象增加一个属性count,保存购物车中对应商品的数量
            sku.count = int(count)
            skus.append(sku)
            # 累计商品的总数目和总价格
            total_count += int(count)
            total_price += sku.amount

        # 组织参数
        context = {
            'total_count': total_count,
            'total_price': total_price,
            'skus': skus,
        }

        return render(request, 'cart.html', context)


class CartAddView(LoginRequiredMixin, View):
    """购物车记录添加"""

    def post(self, request):
        """购物车记录添加"""
        # 检验用户是否登录
        user = request.user
        if not user.is_authenticated:
            # 用户未登录
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})
        # 校验添加的商品数量
        try:
            count = int(count)
        except Exception:
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})
        # if count <= 0:
        #     return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})
        # 校验商品是否存在
        try:
            sku = GoodsSKU.objects.get(id=sku_id, is_delete=False)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理 添加购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # 先尝试获取sku_id的值-> hget(name,value)
        # 如果sku_id在hash中不存在，hget返回none
        cart_count = conn.hget(cart_key, sku_id)
        if cart_count:
            # 累加购物车商品的数目
            count += int(cart_count)
        # 检验商品库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})

        conn.hset(cart_key, sku_id, count)
        # 设置hash中sku_id对应的值  hset(name,key,value)
        # hset->如果sku_id已经存在，更新数据，如果sku_id不存在，添加数据
        # 计算用户购物车商品的条目数
        total_count = conn.hlen(cart_key)

        # 返回应答
        return JsonResponse({'res': 5, 'total_count': total_count, 'message': '添加成功'})


# 采用ajax post请求
# 前端需要传递的参数：商品id(sku_id),更新的商品数量(amount)
class CartUpdateView(LoginRequiredMixin, View):
    """购物车记录更新"""

    def post(self, request):
        # 检验用户是否登录
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        # 接收数据
        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据校验
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})
        try:
            count = int(count)
        except Exception:
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})
        if count < 0:
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 业务处理 更新购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})
        # 更新
        conn.hset(cart_key, sku_id, count)

        # 计算用户购物车中商品的总件数
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        # 返回应答
        return JsonResponse({'res': 5, 'total_count': total_count, 'message': '添加成功'})


# 采用ajax post请求
# 前端需要传递的参数：商品id(sku_id)
class CartDeleteView(LoginRequiredMixin, View):
    """购物车记录删除"""

    def post(self, request):
        # 校验用户是否登录
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})
        # 接收参数
        sku_id = request.POST.get('sku_id')

        # 数据的校验
        if not sku_id:
            return JsonResponse({'res': 1, 'errmsg': '无效的商品id'})

        # 校验商品是否存在
        try:
            GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 2, 'errmsg': '商品不存在'})

        # 业务处理 删除购物车记录
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        # 删除 hdel
        conn.hdel(cart_key, sku_id)

        # 计算用户购物车中商品的总件数
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        # 返回应答
        return JsonResponse({'res': 3, 'total_count': total_count, 'message': '删除成功'})

apps/chart/views.py
import json
from random import randrange
from django.http import HttpResponse
from pyecharts.options import AxisOpts
from rest_framework.views import APIView
from pyecharts.charts import Bar
from pyecharts import options as opts
from apps.goods.models import GoodsSKU, GoodsType
from django.db import connection


# Create your views here.
def response_as_json(data):
    json_str = json.dumps(data)
    response = HttpResponse(
        json_str,
        content_type="application/json",
    )
    response["Access-Control-Allow-Origin"] = "*"
    return response


def json_response(data, code=200):
    data = {
        "code": code,
        "msg": "success",
        "data": data,
    }
    return response_as_json(data)


def json_error(error_string="error", code=500, **kwargs):
    data = {
        "code": code,
        "msg": error_string,
        "data": {}
    }
    data.update(kwargs)
    return response_as_json(data)


JsonResponse = json_response
JsonError = json_error


def bar_base() -> Bar:
    skus = GoodsSKU.objects.filter(is_delete=False).order_by('-sales')[:10]
    c = (
        Bar()
        .add_xaxis([sku.spu.name + sku.category for sku in skus])
        .add_yaxis('销量', [sku.sales for sku in skus], bar_width=50)
        .set_global_opts(title_opts=opts.TitleOpts(title="销量前十"),
                         xaxis_opts=AxisOpts(axislabel_opts={'interval':'0', 'rotate':15}))
        .dump_options_with_quotes()
    )
    return c

def pie_base() -> Bar:
    typesales = my_custom_sql('''select type.goods_type,sum(sku.sales) as totalsale
from ec_goods_sku as sku join ec_goods_spu as spu
on sku.spu_id = spu.id
join ec_goods_type as type on spu.type_id = type.id
where sku.is_delete=false and spu.is_delete=false
group by spu.type_id
order by totalsale desc
limit 10;''')
    c = (
        Bar()
        .add_xaxis([typesale[0] for typesale in typesales])
        .add_yaxis('分类销量', [typesale[1] for typesale in typesales], bar_width=50)
        .set_global_opts(title_opts=opts.TitleOpts(title="分类销量"),
                         xaxis_opts=AxisOpts(axislabel_opts={'interval':'0', 'rotate':15}))
        .dump_options_with_quotes()
    )

    return c

class ChartView(APIView):
    def get(self, request, *args, **kwargs):
        return JsonResponse(json.loads(bar_base()))

class PieChartView(APIView):
    def get(self, request, *args, **kwargs):
        return JsonResponse(json.loads(pie_base()))

class IndexView(APIView):
    def get(self, request, *args, **kwargs):
        return HttpResponse(content=open("./templates/charts.html").read())


def my_custom_sql(sql):
    with connection.cursor() as cursor:
        cursor.execute(sql)
        row = cursor.fetchall()
    return row

templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
{# 首页 登录页 注册页 #}
{% load static %}
<head>
    <meta charset="UTF-8">
    {# 网页标题内容块 #}
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {# 网页头部引入文件块js #}
    {% block topfiles %}{% endblock topfiles %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到天天图书!</div>
            <div class="fr">
                {% if user.is_authenticated %}
                    <div class="login_btn fl">
                        欢迎您：<em>{{ user.username }}</em>
                        <span>|</span>
                        <a href="{% url 'user:logout' %}">退出</a>
                    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="{% url 'user:login' %}">登录</a>
                        <span>|</span>
                        <a href="{% url 'user:register' %}">注册</a>
                    </div>
                {% endif %}
                <div class="user_link fl">
                    <span>|</span>
                    <a href="{% url 'user:profile' %}">用户中心</a>
                    <span>|</span>
                    <a href="{% url 'cart:show' %}">我的购物车</a>
                    <span>|</span>
                    <a href="{% url 'user:order' 1 %}">我的订单</a>
                </div>
            </div>
        </div>
    </div>
{% endblock header_con %}
{# 网页顶部搜索框块 #}
{% block search_bar %}
    <div class="search_bar clearfix">
        <a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}" alt="logo"></a>
        <div class="search_con fl">
             <form action="/search" method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
        </div>
        <div class="guest_cart fr">
            <a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
            <div class="goods_count fl" id="show_count">{{ cart_count }}</div>
        </div>
    </div>
{% endblock search_bar %}
{# 网页主体内容快 #}
{% block body %}{% endblock body %}
{# 网页底部html元素块 #}
{% block bottom %}{% endblock bottom %}
<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2022 天天图书信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****999 豫ICP备*******9号</p>
</div>
{# 网页底部引入文件块 #}
{% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>

templates/base_detail_list.html
{# 详情页 列表页 #}
{% extends 'base.html' %}
{# 网页主体内容快 #}
{% block body %}
<div class="navbar_con">
    <div class="navbar clearfix">
        <div class="subnav_con fl">
            <h1>全部商品分类</h1>
            <span></span>
            <ul class="subnav">
                {% for goods_type in goods_types %}
                    <li><a href="{% url 'goods:list' goods_type.id 1 %}" class="{{ goods_type.logo }}">{{ goods_type.goods_type }}</a></li>
                {% endfor %}
            </ul>
        </div>
        <ul class="navlist fl">
            <li><a href="{% url 'goods:index' %}">首页</a></li>
            <li class="interval">|</li>
            <li><a href="#">热销</a></li>
        </ul>
    </div>
</div>
{# 详情页、列表页主体内容块 #}
{% block main_content %}{% endblock main_content %}
{% endblock body %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}天天图书-首页{% endblock title %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}

{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="#">热销</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			{% for goods_type in goods_types %}
                <li><a href="#model0{{ forloop.counter }}" class="{{ goods_type.logo }}">{{ goods_type.goods_type }}</a></li>
			{% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for banner in index_goods_banners %}
				    <li><a href="{% url 'goods:detail' banner.sku.spu.id banner.sku.id %}"><img src="{{ banner.image.url }}" alt="幻灯片"></a></li>
				{% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for banner in promotion_banners %}
			    <a href="{{ banner.url }}"><img src="{{ banner.image.url }}" alt="{{ banner.name }}"></a>
            {% endfor %}
		</div>
	</div>

    {% for goods_type in goods_types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ goods_type.goods_type }}</h3>
			<a href="{% url 'goods:list' goods_type.id 1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ goods_type.image.url }}" alt="{{ goods_type.goods_type }}"></div>
			<ul class="goods_list fl">
				{% for spu in goods_type.spu %}
				<li>
					<a href="{% url 'goods:detail' spu.id spu.sku.id %}"><img src="{{ spu.sku.image.image.url }}" alt="商品图片"></a>
					<h4><a href="{% url 'goods:detail' spu.id spu.sku.id %}">{{ spu.name }}</a></h4>
					<div class="prize">¥ {{ spu.sku.price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
{% endblock body %}

templates/list.html
{% extends 'base_detail_list.html' %}
{% block title %}天天图书-商品列表{% endblock title %}
{% block main_content %}
	<div class="breadcrumb">
		<span>全部分类</span>
		<span>></span>
		<span>{{ goods_type.goods_type }}</span>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' sku.spu.id sku.id %}">
							{% for img in sku.images %}
							{% if 1 == forloop.counter %}
							<img src="{{ img.image.url }}" alt="商品图片">
							{% endif %}
							{% endfor %}
						</a>
						<h4><a href="{% url 'goods:detail' sku.spu.id sku.id %}">{{ sku.spu.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' goods_type.id 1 %}" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' goods_type.id 1 %}?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' goods_type.id 1 %}?sort=hot" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for sku in skus_page %}
				<li>
					<a href="{% url 'goods:detail' sku.spu.id sku.id %}">
						{% for img in sku.images %}
						{% if 1 == forloop.counter %}
						<img src="{{ img.image.url }}" alt="商品图片">
						{% endif %}
						{% endfor %}
					</a>
					<h4><a href="{% url 'goods:detail' sku.spu.id sku.id %}">{{ sku.spu.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
						<span class="unit">{{ sku.unite }}</span>
					</div>
				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
                {% if skus_page.has_previous %}
				<a href="{% url 'goods:list' goods_type.id skus_page.previous_page_number %}?sort={{ sort }}"><上一页</a>
                {% endif %}
                {% for pindex in pages %}
                    {% if pindex == skus_page.number %}
				        <a href="{% url 'goods:list' goods_type.id pindex %}?sort={{ sort }}" class="active">{{ pindex }}</a>
                    {% else %}
				        <a href="{% url 'goods:list' goods_type.id pindex %}?sort={{ sort }}">{{ pindex }}</a>
                    {% endif %}
                {% endfor %}
                {% if skus_page.has_next %}
				<a href="{% url 'goods:list' goods_type.id skus_page.next_page_number %}?sort={{ sort }}">下一页></a>
                {% endif %}
			</div>
		</div>
	</div>

{% endblock main_content %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}天天图书-登录{% endblock title %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
	<div class="login_top clearfix">
		<a href="{% url 'goods:index' %}" class="login_logo"><img src="{% static 'images/logo02.png' %}"></a>
        <p style="font-family: 'Adobe 宋体 Std L';  font-size: 24px; margin-left: 180px; margin-top: -40px; color: red">欢迎登录</p>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>   <!--注册页书本-->
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'user:register' %}">立即注册</a>
				</div>
				<div class="form_input">
                    {# 不设置表单action时，提交表单时，会向浏览器地址栏中的地址提交数据 #}
					<form method="post">
						{% csrf_token %}
						<input type="text" name="username" value="{{ username }}" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="password" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" {{ checked }}>
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
                <div style="margin-top: -30px;text-align: center;font-size: 14px;">
                   <span style="color: red;">{{ errmsg }}</span>
                </div>

			</div>
		</div>
	</div>

{% endblock body %}

templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block title %}天天图书-注册{% endblock title %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
{% endblock topfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/logo02.png' %}"></a>
			<div class="reg_slogan">足不出户  ·  阅读每一天</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'user:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form id="reg_form" method="post" action="{% url 'user:register' %}">
					{% csrf_token %}
                    <input type="hidden" id="captcha_uuid" name="captcha_uuid" value="#">
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="username" id="username">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>密码:</label>
						<input type="password" name="password" id="password">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="confirm_pwd" id="confirm_pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
                    <li>
                        <img src="#" id="captcha_im" alt="验证码" heighth="65px" width="100px">
                        <input type="text" name="captcha" id="captcha" placeholder="请输入计算结果" style="width: 250px;float: right;">
                        <span class="error_tip">提示信息</span>
                    </li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天图书用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>				
				</form>
				<span style="color: red">{{ errmsg }}</span>
			</div>

		</div>

	</div>
{% endblock body %}

templates/user_center_info.html
{% extends 'base_user_center.html' %}
{% block right_content %}
<div class="right_content clearfix">
    <div class="info_con clearfix">
        <h3 class="common_title2">基本信息</h3>
        <ul class="user_info_list">
            <li><span>用户名：</span>{{ user.username }}</li>
            <li><span>昵称：</span>{{ user.nickname }}</li>
            <li><span>性别：</span>{{ user.gender }}</li>
            <li><span>生日：</span>{{ user.birthday }}</li>
            {% if address %}
                <li><span>联系方式：</span>{{ address.phone }}</li>
                <li><span>联系地址：</span>{{ address.address }}</li>
            {% else %}
                <li><span>联系方式：</span>无默认</li>
                <li><span>联系地址：</span>无默认</li>
            {% endif %}
        </ul>
    </div>

    <h3 class="common_title2">最近浏览</h3>
    <div class="has_view_list">
        <ul class="goods_type_list clearfix">
            {% for goods in goods_li %}
                <li>
                    <a href="{% url 'goods:detail' goods.spu.id goods.id %}">
                        {% for goods_img in goods.images %}
                        {% if forloop.counter == 1 %}
                        <img src="{{ goods_img.image.url }}">
                        {% endif %}
                        {% endfor %}
                    </a>
                    <h4><a href="{% url 'goods:detail' goods.spu.id goods.id %}">{{ goods.name }}</a></h4>
                    <div class="operate">
                        <span class="prize">￥{{ goods.price }}</span>
                        <span class="unit">{{ goods.unite }}</span>
                    </div>
                </li>
            {% empty %}
                无历史浏览记录
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock right_content %}